### ISSUE TITLE
Offset option for columns?

### ISSUE THREAD

**Issue by maxx1128** [NeutronCSS/neutroncss#35]
The only major feature I feel is missing from here compared to other grids is being able to offset columns by a certain number of others. For example, having a 10-column div offset by one column so it's centered at the smaller width. I couldn't find a reference to this in the documentation.

Are there plans to add this specific feature sometime in the future or did I overlook it under a different alias?

**Comment by chris-muller** [comment]
Hey Max,

I saw your tweet earlier today about offsets and it's something I have started looking into, and should have a more concrete answer over the next couple weeks.

For your specific example, I'd currently implement it with something like this:

``` scss
div{
  @include container-width(80%);
  @include container-align(center);
}
```

Or if this div is going to contain columns, you could use this:

``` scss
div{
  @include columns(4, $container-width: 80%, $container-align: center);
}
```

Which would give you a four column layout inside the centered div.
