### ISSUE TITLE
Finalise Syntax for Flexbox support

### ISSUE THREAD

**Issue by chris-muller** [NeutronCSS/neutroncss#36]
# Current State

Neutron currently uses the following mixins for 'floatbox' layout columns:
- `columns()`
- `column()`
- `col()`
# Suggested Syntax for Flexbox

These mixins would try to match the behavior of floatbox mixins as closely as practical to allow for easy migration from floatbox layout systems to flexbox. 
- `flex-columns()`
- `flex-column()`
- `flex-col()`
# Potential future changes and impact

Once flexbox gains more mainstream support and usage, `columns()` could be changed to `float-columns()` and `flex-columns()` changed to `columns()`.
## Reducing future impact

Perhaps add floatbox column aliases now `float-columns()` to allow people to be more specific and clear with their column layout usage.
### Grid support

If the draft specification for the CSS grid layout properties matures in the future, `grid-columns()` may be added in the future.

**Comment by porcelanosa** [comment]
is it stable?

**Comment by chris-muller** [comment]
Flex box support will be finalised and getting added in the next week or two, depending on how much time I have to test it.
