### ISSUE TITLE
Neutron vs Susy?

### ISSUE THREAD

**Issue by rathishcholarajan** [NeutronCSS/neutroncss#39]
Hey guys. Sounds awesome. I would like to understand how this is different from Susy?

**Comment by chris-muller** [comment]
Hey,

They both use Sass and serve the same basic purpose (creating a responsive web layout), but I think some of the main points of differentiation are:
- Neutron has a much more streamlined implementation. Just start declaring your columns and you're done, no need for config variables, or declaring containers.
- Nested columns work identically to any other column, you don't need additional configuration options for it to work correctly.
- Neutron will allow easier transition to flexbox as it becomes more widely spread. Our upcoming flexbox module will use almost identical syntax, making the transition much simpler and easier to pick up.

If you have any other questions feel free to ask.

**Comment by rathishcholarajan** [comment]
Great, thanks!
