### ISSUE TITLE
Breakpoins settings

### ISSUE THREAD

**Issue by porcelanosa** [NeutronCSS/neutroncss#45]
Hi, I use your grid system in one my private site. I use branch with [flexbox features ](https://github.com/NeutronCSS/neutroncss/tree/feature/flexbox) 
And I very often need some breakpoint like _max-width_
And use **mobile** and then use **phablet** with same parametrs   is`t comfortable

``` sass
    @include breakpoint(mobile) {
        @include flex-col(1, $flush-margin: false, $target: 'div');
    }
    @include breakpoint(phablet) {
        @include flex-col(1, $flush-margin: false, $target: 'div');
    }
```

I set custom breakpoint 

``` scss
to-phablet:             createBreakpoint(0, $neutron-phablet-max), //  below 767 
```

But I think, You may set variables on different file... or set mixin for use compound expression like `mobile AND phablet` - it`ll more visual 

Thax for your job

**Comment by B7th** [comment]
I made a pull request adding to-phablet, to-tablet, to-desktop-sml and to-desktop-mid which seems to suit the needs!

**Comment by chris-muller** [comment]
Getting the logic to work reliably would involve a fair amount of effort and be prone to bugs I think. The previously mentioned change has been merged into the main branch of Neutron however, you can find more information on the docs page, hopefully this fulfills your needs.

http://neutroncss.com/docs/#media-query
