### ISSUE TITLE
Overriding defaults?

### ISSUE THREAD

**Issue by klickreflex** [NeutronCSS/neutroncss#56]
Hey there,

I'm trying Neutron and likes it a lot so far, but some things are still a bit unclear to me.

For example, how can I change the container-max-width globally? It can't be the solution to append it to  every column() call as a parameter, can it? The same is true with all parameters that have default values, such as gutters. 

Thanks for clarifying

**Comment by chris-muller** [comment]
I have added default configuration settings to the development branch of the project. It's not live yet as I'm still testing some aspects of how flexbox support is implemented.

Once it goes live the docs page will be updated to include specifics. You could try out the development branch but keep in mind something might end up changing, especially flexbox-related features.
