### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by SxDx** [NeutronCSS/neutroncss#59]
I would like to use neutron in an upcoming project and was wondering if it is still supported / in active development because there has not been much activity in the recent months.

**Comment by ForsakenHarmony** [comment]
it's dead ...

**Comment by chris-muller** [comment]
Sorry for the late reply, but yes. Neutron is no longer in active development.

I'd be happy to merge in any bugfixes that get submitted but with the widespread support of flexbox, and upcoming wider support for display:grid, which are both superior to bootstrap-style layout frameworks, I don't feel Neutron has much to offer that isn't provided natively.
